language: ruby
rvm:
  - 2.6.3
services:
  - mysql
env:
  - DB=mysql2
before_install:
  - gem install bundler
gemfile:
  - Gemfile
script:
  - rake db:schema:load
  - bundle exec rspec spec/
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS poro_development;'
bundler_args: --binstubs=./bundler_stubs
