language: ruby
rvm:
  - 2.6.3
env:
  - DB=mysql2
before_install:
  - gem install bundler
gemfile:
  - Gemfile
script:
  - bundle exec rake db:create db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - mysql -e 'create database poro_development'
bundler_args: --binstubs=./bundler_stubs
