language: ruby
rvm:
  - 2.6.3
services:
  - mysql
env:
  - DB=mysql2
before_install:
  - gem install bundler
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('mypassword') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pmypassword
  - sudo service mysql restart
gemfile:
  - Gemfile
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - mysql -e 'create database poro_test'
bundler_args: --binstubs=./bundler_stubs
