version: '3'
services:
  shastic_challenge:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    links:
      - mysql
    command: ruby api_server.rb
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    ports:
      - 3306:3306
    volumes:
      - ./:/app
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
