default: &default
  adapter: mysql2
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'mypassword'
  host: localhost

development:
  <<: *default
  database: 'poro_development'

test:
  <<: *default
  database: 'poro_test'

test:
  adapter: mysql2
  database: 'poro_test'
  username: travis
  encoding: utf8
